# Generated by Django 3.0.6 on 2020-05-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='reg_users',
        ),
    ]
